sudo: required
dist: trusty
branches:
  only:
    - master

language: python
python:
  - "2.7"
#  - "3.6"

env:
  global:
    - GOPATH=$HOME/go
    - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
    - PYTHONPATH=${PYTHONPATH}:${HOME}/git/common-robotics
    - PYTHONWARNINGS="ignore"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install autoconf automake libtool curl make g++ unzip
  - sudo apt-get install golang-goprotobuf-dev
  - bin/install-protobuf.sh
#  - gimme 1.8

install:
  - make install-common
  - make install-py
  - make install-go
#  - make codegen

before_script:
  - make test_server &
  - make http_proxy &

script:
  - ./http_distance_client.py --count 100
  - ./distance_client.py --count 100

