language: python
python:
  - "2.7"
#  - "3.6"

#go:
#  - 1.8
#  - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gcc
  - sudo apt-get install go

install:
  - pip install --user --upgrade pip
  - pip install --user -r requirements.txt
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - go get -u github.com/golang/protobuf/protoc-gen-go


script: pytest

branches:
  only:
    - master
