sudo: required
dist: trusty
language: python
python:
  - "2.7.13"
#  - "3.6"

env:
  global:
    - GOPATH=$HOME/go
    - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
    - PYTHONPATH=${PYTHONPATH}:~/common-robotics
    - PYTHONWARNINGS="ignore"

before_install:
  - sudo apt-get -qq update
#  - sudo apt-get install golang

install:
  - git clone https://github.com/athenian-robotics/common-robotics.git
  - gimme 1.8
#  - sudo pip install --upgrade pip
  - pip install -r server-requirements.txt
  - pip install -r client-requirements.txt
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - go get -u github.com/golang/protobuf/protoc-gen-go
#  - go get -u github.com/googleapis/googleapis
  - go get -u google.golang.org/grpc


before_script:
  - make test_server
  - make http_proxy

script:
  - ./http_distance_client.py --count 10
  - ./distance_client.py --count 10

branches:
  only:
    - master
