// Code generated by protoc-gen-go.
// source: proto/distance_service.proto
// DO NOT EDIT!

/*
Package distance_server is a generated protocol buffer package.

It is generated from these files:
	proto/distance_service.proto

It has these top-level messages:
	ClientInfo
	ServerInfo
	Distance
*/
package distance_server

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
    "golang.org/x/net/context"
    "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientInfo struct {
    Info string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *ClientInfo) Reset() {
    *m = ClientInfo{}
}
func (m *ClientInfo) String() string {
    return proto.CompactTextString(m)
}
func (*ClientInfo) ProtoMessage() {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
    return fileDescriptor0, []int{0}
}

func (m *ClientInfo) GetInfo() string {
    if m != nil {
        return m.Info
    }
    return ""
}

type ServerInfo struct {
    Info string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *ServerInfo) Reset() {
    *m = ServerInfo{}
}
func (m *ServerInfo) String() string {
    return proto.CompactTextString(m)
}
func (*ServerInfo) ProtoMessage() {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
    return fileDescriptor0, []int{1}
}

func (m *ServerInfo) GetInfo() string {
    if m != nil {
        return m.Info
    }
    return ""
}

type Distance struct {
    Id       int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
    Ts       int64 `protobuf:"varint,2,opt,name=ts" json:"ts,omitempty"`
    Elapsed  int64 `protobuf:"varint,3,opt,name=elapsed" json:"elapsed,omitempty"`
    Distance int32 `protobuf:"varint,4,opt,name=distance" json:"distance,omitempty"`
}

func (m *Distance) Reset() {
    *m = Distance{}
}
func (m *Distance) String() string {
    return proto.CompactTextString(m)
}
func (*Distance) ProtoMessage() {}
func (*Distance) Descriptor() ([]byte, []int) {
    return fileDescriptor0, []int{2}
}

func (m *Distance) GetId() int32 {
    if m != nil {
        return m.Id
    }
    return 0
}

func (m *Distance) GetTs() int64 {
    if m != nil {
        return m.Ts
    }
    return 0
}

func (m *Distance) GetElapsed() int64 {
    if m != nil {
        return m.Elapsed
    }
    return 0
}

func (m *Distance) GetDistance() int32 {
    if m != nil {
        return m.Distance
    }
    return 0
}

func init() {
    proto.RegisterType((*ClientInfo)(nil), "distance_server.ClientInfo")
    proto.RegisterType((*ServerInfo)(nil), "distance_server.ServerInfo")
    proto.RegisterType((*Distance)(nil), "distance_server.Distance")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DistanceService service

type DistanceServiceClient interface {
    RegisterClient(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*ServerInfo, error)
    GetDistances(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (DistanceService_GetDistancesClient, error)
    GetDistance(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*Distance, error)
}

type distanceServiceClient struct {
    cc *grpc.ClientConn
}

func NewDistanceServiceClient(cc *grpc.ClientConn) DistanceServiceClient {
    return &distanceServiceClient{cc}
}

func (c *distanceServiceClient) RegisterClient(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*ServerInfo, error) {
    out := new(ServerInfo)
    err := grpc.Invoke(ctx, "/distance_server.DistanceService/registerClient", in, out, c.cc, opts...)
    if err != nil {
        return nil, err
    }
    return out, nil
}

func (c *distanceServiceClient) GetDistances(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (DistanceService_GetDistancesClient, error) {
    stream, err := grpc.NewClientStream(ctx, &_DistanceService_serviceDesc.Streams[0], c.cc, "/distance_server.DistanceService/getDistances", opts...)
    if err != nil {
        return nil, err
    }
    x := &distanceServiceGetDistancesClient{stream}
    if err := x.ClientStream.SendMsg(in); err != nil {
        return nil, err
    }
    if err := x.ClientStream.CloseSend(); err != nil {
        return nil, err
    }
    return x, nil
}

type DistanceService_GetDistancesClient interface {
    Recv() (*Distance, error)
    grpc.ClientStream
}

type distanceServiceGetDistancesClient struct {
    grpc.ClientStream
}

func (x *distanceServiceGetDistancesClient) Recv() (*Distance, error) {
    m := new(Distance)
    if err := x.ClientStream.RecvMsg(m); err != nil {
        return nil, err
    }
    return m, nil
}

func (c *distanceServiceClient) GetDistance(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*Distance, error) {
    out := new(Distance)
    err := grpc.Invoke(ctx, "/distance_server.DistanceService/getDistance", in, out, c.cc, opts...)
    if err != nil {
        return nil, err
    }
    return out, nil
}

// Server API for DistanceService service

type DistanceServiceServer interface {
    RegisterClient(context.Context, *ClientInfo) (*ServerInfo, error)
    GetDistances(*ClientInfo, DistanceService_GetDistancesServer) error
    GetDistance(context.Context, *google_protobuf1.Empty) (*Distance, error)
}

func RegisterDistanceServiceServer(s *grpc.Server, srv DistanceServiceServer) {
    s.RegisterService(&_DistanceService_serviceDesc, srv)
}

func _DistanceService_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
    in := new(ClientInfo)
    if err := dec(in); err != nil {
        return nil, err
    }
    if interceptor == nil {
        return srv.(DistanceServiceServer).RegisterClient(ctx, in)
    }
    info := &grpc.UnaryServerInfo{
        Server:     srv,
        FullMethod: "/distance_server.DistanceService/RegisterClient",
    }
    handler := func(ctx context.Context, req interface{}) (interface{}, error) {
        return srv.(DistanceServiceServer).RegisterClient(ctx, req.(*ClientInfo))
    }
    return interceptor(ctx, in, info, handler)
}

func _DistanceService_GetDistances_Handler(srv interface{}, stream grpc.ServerStream) error {
    m := new(ClientInfo)
    if err := stream.RecvMsg(m); err != nil {
        return err
    }
    return srv.(DistanceServiceServer).GetDistances(m, &distanceServiceGetDistancesServer{stream})
}

type DistanceService_GetDistancesServer interface {
    Send(*Distance) error
    grpc.ServerStream
}

type distanceServiceGetDistancesServer struct {
    grpc.ServerStream
}

func (x *distanceServiceGetDistancesServer) Send(m *Distance) error {
    return x.ServerStream.SendMsg(m)
}

func _DistanceService_GetDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
    in := new(google_protobuf1.Empty)
    if err := dec(in); err != nil {
        return nil, err
    }
    if interceptor == nil {
        return srv.(DistanceServiceServer).GetDistance(ctx, in)
    }
    info := &grpc.UnaryServerInfo{
        Server:     srv,
        FullMethod: "/distance_server.DistanceService/GetDistance",
    }
    handler := func(ctx context.Context, req interface{}) (interface{}, error) {
        return srv.(DistanceServiceServer).GetDistance(ctx, req.(*google_protobuf1.Empty))
    }
    return interceptor(ctx, in, info, handler)
}

var _DistanceService_serviceDesc = grpc.ServiceDesc{
    ServiceName: "distance_server.DistanceService",
    HandlerType: (*DistanceServiceServer)(nil),
    Methods: []grpc.MethodDesc{
        {
            MethodName: "registerClient",
            Handler:    _DistanceService_RegisterClient_Handler,
        },
        {
            MethodName: "getDistance",
            Handler:    _DistanceService_GetDistance_Handler,
        },
    },
    Streams: []grpc.StreamDesc{
        {
            StreamName:    "getDistances",
            Handler:       _DistanceService_GetDistances_Handler,
            ServerStreams: true,
        },
    },
    Metadata: "proto/distance_service.proto",
}

func init() {
    proto.RegisterFile("proto/distance_service.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
    // 305 bytes of a gzipped FileDescriptorProto
    0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xcb, 0x4e, 0xc3, 0x30,
    0x10, 0x24, 0x6e, 0x81, 0xb2, 0x94, 0x56, 0x5a, 0x01, 0x0a, 0x69, 0x0f, 0x55, 0x4e, 0x3d, 0x39,
    0x3c, 0x3e, 0x01, 0x38, 0x20, 0x71, 0x4a, 0x25, 0xae, 0x25, 0x6d, 0x36, 0x91, 0xa5, 0x60, 0x47,
    0xb1, 0xa9, 0xc4, 0x95, 0x5f, 0xe0, 0xc2, 0x7f, 0xf1, 0x0b, 0x7c, 0x08, 0x8a, 0x53, 0xb7, 0x85,
    0x8a, 0xde, 0x32, 0x3b, 0xeb, 0x99, 0xcc, 0x0e, 0x0c, 0xcb, 0x4a, 0x19, 0x15, 0xa5, 0x42, 0x9b,
    0x44, 0xce, 0x69, 0xaa, 0xa9, 0x5a, 0x88, 0x39, 0x71, 0x3b, 0xc6, 0xfe, 0xaf, 0x39, 0x55, 0xc1,
    0x30, 0x57, 0x2a, 0x2f, 0x28, 0x4a, 0x4a, 0x11, 0x25, 0x52, 0x2a, 0x93, 0x18, 0xa1, 0xa4, 0x6e,
    0xd6, 0x83, 0xc1, 0x92, 0xb5, 0x68, 0xf6, 0x9a, 0x45, 0xf4, 0x52, 0x9a, 0xb7, 0x86, 0x0c, 0x47,
    0x00, 0xb7, 0x85, 0x20, 0x69, 0x1e, 0x64, 0xa6, 0x10, 0xa1, 0x2d, 0x64, 0xa6, 0x7c, 0x6f, 0xe4,
    0x8d, 0x8f, 0x62, 0xfb, 0x5d, 0x6f, 0x4c, 0xac, 0xcd, 0xbf, 0x1b, 0xcf, 0xd0, 0xb9, 0x5b, 0xfe,
    0x11, 0xf6, 0x80, 0x89, 0xd4, 0xb2, 0xfb, 0x31, 0x13, 0x69, 0x8d, 0x8d, 0xf6, 0xd9, 0xc8, 0x1b,
    0xb7, 0x62, 0x66, 0x34, 0xfa, 0x70, 0x48, 0x45, 0x52, 0x6a, 0x4a, 0xfd, 0x96, 0x1d, 0x3a, 0x88,
    0x01, 0x74, 0x5c, 0x2e, 0xbf, 0x6d, 0xdf, 0xaf, 0xf0, 0xf5, 0x27, 0x83, 0xbe, 0xb3, 0x98, 0x34,
    0xb7, 0xc0, 0x47, 0xe8, 0x55, 0x94, 0x0b, 0x6d, 0xa8, 0x6a, 0x12, 0xe0, 0x80, 0xff, 0x39, 0x0c,
    0x5f, 0x47, 0x0b, 0xb6, 0xc9, 0x75, 0xaa, 0x70, 0x0f, 0xa7, 0xd0, 0xcd, 0xc9, 0x38, 0x0f, 0xbd,
    0x5b, 0xeb, 0x62, 0x8b, 0x74, 0x0f, 0xc3, 0xb3, 0xf7, 0xaf, 0xef, 0x0f, 0xd6, 0xc7, 0x93, 0x68,
    0x71, 0xb5, 0xea, 0x4f, 0x5f, 0x7a, 0xf8, 0x04, 0xc7, 0x1b, 0x06, 0x78, 0xce, 0x9b, 0x56, 0xb8,
    0x6b, 0x85, 0xdf, 0xd7, 0xad, 0xec, 0x92, 0x3e, 0xb5, 0xd2, 0x3d, 0xec, 0x6e, 0x4a, 0xcf, 0x0e,
    0xac, 0xc0, 0xcd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xdf, 0x1a, 0xce, 0x33, 0x02, 0x00,
    0x00,
}
