# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import grpc

import proto.distance_service_pb2 as proto_dot_distance__service__pb2


class DistanceServiceStub(object):
    def __init__(self, channel):
        """Constructor.
    
        Args:
          channel: A grpc.Channel.
        """
        self.registerClient = channel.unary_unary(
            '/distance_server.DistanceService/registerClient',
            request_serializer=proto_dot_distance__service__pb2.ClientInfo.SerializeToString,
            response_deserializer=proto_dot_distance__service__pb2.ServerInfo.FromString,
        )
        self.getDistances = channel.unary_stream(
            '/distance_server.DistanceService/getDistances',
            request_serializer=proto_dot_distance__service__pb2.ClientInfo.SerializeToString,
            response_deserializer=proto_dot_distance__service__pb2.Distance.FromString,
        )
        self.getDistance = channel.unary_unary(
            '/distance_server.DistanceService/getDistance',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=proto_dot_distance__service__pb2.Distance.FromString,
        )


class DistanceServiceServicer(object):
    def registerClient(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDistances(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDistance(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'registerClient': grpc.unary_unary_rpc_method_handler(
            servicer.registerClient,
            request_deserializer=proto_dot_distance__service__pb2.ClientInfo.FromString,
            response_serializer=proto_dot_distance__service__pb2.ServerInfo.SerializeToString,
        ),
        'getDistances': grpc.unary_stream_rpc_method_handler(
            servicer.getDistances,
            request_deserializer=proto_dot_distance__service__pb2.ClientInfo.FromString,
            response_serializer=proto_dot_distance__service__pb2.Distance.SerializeToString,
        ),
        'getDistance': grpc.unary_unary_rpc_method_handler(
            servicer.getDistance,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=proto_dot_distance__service__pb2.Distance.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'distance_server.DistanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
