// Code generated by protoc-gen-go.
// source: pb/distance_server.proto
// DO NOT EDIT!

/*
Package distance_server is a generated protocol buffer package.

It is generated from these files:
	pb/distance_server.proto

It has these top-level messages:
	ClientInfo
	ServerInfo
	Distance
*/
package distance_server

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
    "golang.org/x/net/context"
    "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientInfo struct {
    Info string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *ClientInfo) Reset() {
    *m = ClientInfo{}
}
func (m *ClientInfo) String() string {
    return proto.CompactTextString(m)
}
func (*ClientInfo) ProtoMessage() {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
    return fileDescriptor0, []int{0}
}

func (m *ClientInfo) GetInfo() string {
    if m != nil {
        return m.Info
    }
    return ""
}

type ServerInfo struct {
    Info string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *ServerInfo) Reset() {
    *m = ServerInfo{}
}
func (m *ServerInfo) String() string {
    return proto.CompactTextString(m)
}
func (*ServerInfo) ProtoMessage() {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
    return fileDescriptor0, []int{1}
}

func (m *ServerInfo) GetInfo() string {
    if m != nil {
        return m.Info
    }
    return ""
}

type Distance struct {
    Id       int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
    Ts       int64 `protobuf:"varint,2,opt,name=ts" json:"ts,omitempty"`
    Elapsed  int64 `protobuf:"varint,3,opt,name=elapsed" json:"elapsed,omitempty"`
    Distance int32 `protobuf:"varint,4,opt,name=distance" json:"distance,omitempty"`
}

func (m *Distance) Reset() {
    *m = Distance{}
}
func (m *Distance) String() string {
    return proto.CompactTextString(m)
}
func (*Distance) ProtoMessage() {}
func (*Distance) Descriptor() ([]byte, []int) {
    return fileDescriptor0, []int{2}
}

func (m *Distance) GetId() int32 {
    if m != nil {
        return m.Id
    }
    return 0
}

func (m *Distance) GetTs() int64 {
    if m != nil {
        return m.Ts
    }
    return 0
}

func (m *Distance) GetElapsed() int64 {
    if m != nil {
        return m.Elapsed
    }
    return 0
}

func (m *Distance) GetDistance() int32 {
    if m != nil {
        return m.Distance
    }
    return 0
}

func init() {
    proto.RegisterType((*ClientInfo)(nil), "distance_server.ClientInfo")
    proto.RegisterType((*ServerInfo)(nil), "distance_server.ServerInfo")
    proto.RegisterType((*Distance)(nil), "distance_server.Distance")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DistanceServer service

type DistanceServerClient interface {
    RegisterClient(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*ServerInfo, error)
    GetDistances(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (DistanceServer_GetDistancesClient, error)
    GetDistance(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*Distance, error)
}

type distanceServerClient struct {
    cc *grpc.ClientConn
}

func NewDistanceServerClient(cc *grpc.ClientConn) DistanceServerClient {
    return &distanceServerClient{cc}
}

func (c *distanceServerClient) RegisterClient(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*ServerInfo, error) {
    out := new(ServerInfo)
    err := grpc.Invoke(ctx, "/distance_server.DistanceServer/registerClient", in, out, c.cc, opts...)
    if err != nil {
        return nil, err
    }
    return out, nil
}

func (c *distanceServerClient) GetDistances(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (DistanceServer_GetDistancesClient, error) {
    stream, err := grpc.NewClientStream(ctx, &_DistanceServer_serviceDesc.Streams[0], c.cc, "/distance_server.DistanceServer/getDistances", opts...)
    if err != nil {
        return nil, err
    }
    x := &distanceServerGetDistancesClient{stream}
    if err := x.ClientStream.SendMsg(in); err != nil {
        return nil, err
    }
    if err := x.ClientStream.CloseSend(); err != nil {
        return nil, err
    }
    return x, nil
}

type DistanceServer_GetDistancesClient interface {
    Recv() (*Distance, error)
    grpc.ClientStream
}

type distanceServerGetDistancesClient struct {
    grpc.ClientStream
}

func (x *distanceServerGetDistancesClient) Recv() (*Distance, error) {
    m := new(Distance)
    if err := x.ClientStream.RecvMsg(m); err != nil {
        return nil, err
    }
    return m, nil
}

func (c *distanceServerClient) GetDistance(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*Distance, error) {
    out := new(Distance)
    err := grpc.Invoke(ctx, "/distance_server.DistanceServer/getDistance", in, out, c.cc, opts...)
    if err != nil {
        return nil, err
    }
    return out, nil
}

// Server API for DistanceServer service

type DistanceServerServer interface {
    RegisterClient(context.Context, *ClientInfo) (*ServerInfo, error)
    GetDistances(*ClientInfo, DistanceServer_GetDistancesServer) error
    GetDistance(context.Context, *google_protobuf1.Empty) (*Distance, error)
}

func RegisterDistanceServerServer(s *grpc.Server, srv DistanceServerServer) {
    s.RegisterService(&_DistanceServer_serviceDesc, srv)
}

func _DistanceServer_RegisterClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
    in := new(ClientInfo)
    if err := dec(in); err != nil {
        return nil, err
    }
    if interceptor == nil {
        return srv.(DistanceServerServer).RegisterClient(ctx, in)
    }
    info := &grpc.UnaryServerInfo{
        Server:     srv,
        FullMethod: "/distance_server.DistanceServer/RegisterClient",
    }
    handler := func(ctx context.Context, req interface{}) (interface{}, error) {
        return srv.(DistanceServerServer).RegisterClient(ctx, req.(*ClientInfo))
    }
    return interceptor(ctx, in, info, handler)
}

func _DistanceServer_GetDistances_Handler(srv interface{}, stream grpc.ServerStream) error {
    m := new(ClientInfo)
    if err := stream.RecvMsg(m); err != nil {
        return err
    }
    return srv.(DistanceServerServer).GetDistances(m, &distanceServerGetDistancesServer{stream})
}

type DistanceServer_GetDistancesServer interface {
    Send(*Distance) error
    grpc.ServerStream
}

type distanceServerGetDistancesServer struct {
    grpc.ServerStream
}

func (x *distanceServerGetDistancesServer) Send(m *Distance) error {
    return x.ServerStream.SendMsg(m)
}

func _DistanceServer_GetDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
    in := new(google_protobuf1.Empty)
    if err := dec(in); err != nil {
        return nil, err
    }
    if interceptor == nil {
        return srv.(DistanceServerServer).GetDistance(ctx, in)
    }
    info := &grpc.UnaryServerInfo{
        Server:     srv,
        FullMethod: "/distance_server.DistanceServer/GetDistance",
    }
    handler := func(ctx context.Context, req interface{}) (interface{}, error) {
        return srv.(DistanceServerServer).GetDistance(ctx, req.(*google_protobuf1.Empty))
    }
    return interceptor(ctx, in, info, handler)
}

var _DistanceServer_serviceDesc = grpc.ServiceDesc{
    ServiceName: "distance_server.DistanceServer",
    HandlerType: (*DistanceServerServer)(nil),
    Methods: []grpc.MethodDesc{
        {
            MethodName: "registerClient",
            Handler:    _DistanceServer_RegisterClient_Handler,
        },
        {
            MethodName: "getDistance",
            Handler:    _DistanceServer_GetDistance_Handler,
        },
    },
    Streams: []grpc.StreamDesc{
        {
            StreamName:    "getDistances",
            Handler:       _DistanceServer_GetDistances_Handler,
            ServerStreams: true,
        },
    },
    Metadata: "pb/distance_server.proto",
}

func init() {
    proto.RegisterFile("pb/distance_server.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
    // 301 bytes of a gzipped FileDescriptorProto
    0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xcd, 0x4e, 0xf3, 0x30,
    0x10, 0xfc, 0xe2, 0xf6, 0x83, 0xb2, 0x94, 0x54, 0x5a, 0x01, 0x32, 0x29, 0x87, 0x2a, 0xa7, 0x9e,
    0x12, 0x7e, 0x1e, 0x01, 0x38, 0x20, 0x71, 0x0a, 0x12, 0xd7, 0x92, 0x90, 0x4d, 0x64, 0x29, 0xd8,
    0x51, 0x6c, 0x2a, 0x71, 0xe5, 0x15, 0x38, 0xf0, 0x60, 0xbc, 0x02, 0x0f, 0x82, 0xe2, 0xd4, 0x6d,
    0xd5, 0x8a, 0xde, 0x32, 0x9e, 0xdd, 0x99, 0x9d, 0x0c, 0xf0, 0x3a, 0x8b, 0x73, 0xa1, 0x4d, 0x2a,
    0x5f, 0x68, 0xa6, 0xa9, 0x99, 0x53, 0x13, 0xd5, 0x8d, 0x32, 0x0a, 0x47, 0x1b, 0xcf, 0xc1, 0x79,
    0xa9, 0x54, 0x59, 0x51, 0x9c, 0xd6, 0x22, 0x4e, 0xa5, 0x54, 0x26, 0x35, 0x42, 0x49, 0xdd, 0x8d,
    0x07, 0xe3, 0x05, 0x6b, 0x51, 0xf6, 0x56, 0xc4, 0xf4, 0x5a, 0x9b, 0xf7, 0x8e, 0x0c, 0x27, 0x00,
    0x37, 0x95, 0x20, 0x69, 0xee, 0x65, 0xa1, 0x10, 0xa1, 0x2f, 0x64, 0xa1, 0xb8, 0x37, 0xf1, 0xa6,
    0x07, 0x89, 0xfd, 0x6e, 0x27, 0x1e, 0xad, 0xcd, 0x9f, 0x13, 0xcf, 0x30, 0xb8, 0x5d, 0x5c, 0x84,
    0x3e, 0x30, 0x91, 0x5b, 0xf6, 0x7f, 0xc2, 0x44, 0xde, 0x62, 0xa3, 0x39, 0x9b, 0x78, 0xd3, 0x5e,
    0xc2, 0x8c, 0x46, 0x0e, 0xfb, 0x54, 0xa5, 0xb5, 0xa6, 0x9c, 0xf7, 0xec, 0xa3, 0x83, 0x18, 0xc0,
    0xc0, 0xe5, 0xe2, 0x7d, 0xbb, 0xbf, 0xc4, 0x57, 0x5f, 0x0c, 0x7c, 0x67, 0xd1, 0x1d, 0x83, 0x0f,
    0xe0, 0x37, 0x54, 0x0a, 0x6d, 0xa8, 0xe9, 0x02, 0xe0, 0x38, 0xda, 0xfc, 0x5d, 0xab, 0x64, 0xc1,
    0x36, 0xb9, 0x0a, 0x15, 0xfe, 0xc3, 0x19, 0x0c, 0x4b, 0x32, 0xce, 0x42, 0xef, 0xd6, 0x3a, 0xdb,
    0x22, 0xdd, 0x62, 0x78, 0xf2, 0xf1, 0xfd, 0xf3, 0xc9, 0x46, 0x78, 0x14, 0xcf, 0x2f, 0x97, 0xed,
    0xe9, 0x0b, 0x0f, 0x9f, 0xe0, 0x70, 0xcd, 0x00, 0x4f, 0xa3, 0xae, 0x94, 0xc8, 0x95, 0x12, 0xdd,
    0xb5, 0xa5, 0xec, 0x92, 0x3e, 0xb6, 0xd2, 0x3e, 0x0e, 0xd7, 0xa5, 0xb3, 0x3d, 0x2b, 0x70, 0xfd,
    0x1b, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x0f, 0x5f, 0x9b, 0x2e, 0x02, 0x00, 0x00,
}
